# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More

# Sidebar
sidebar: right
widgets:
- category
- tag
# - tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
gauges_analytics:

favicon:
  ico: icons/favicon.ico
  small: icons/favicon-16x16.png
  medium: icons/favicon-32x32.png
  apple_touch_icon: icons/apple-touch-icon.png
  webmanifest: icons/site.webmanifest
  safari_pinned_tab: icons/safari-pinned-tab.svg
  android_manifest: icons/manifest.json
  ms_browserconfig: icons/browserconfig.xml

twitter:
google_plus:
fb_admins:
fb_app_id:
