# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Japan Office Client Support Blog
subtitle: '日本マイクロソフト Office Client サポート チームのブログです'
description: '日本マイクロソフト Office Client サポート チームのブログです'
keywords:
 - Microsoft
 - Office
 - Support
 - Excel
 - Word
 - PowerPoint
 - OneNote
 - Access
 - マイクロソフト
 - オフィス
 - サポート
author: Office Support Japan
language: ja
timezone: 'asia/Tokyo'

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://officesupportjp.github.io/blog
root: /blog/
permalink: :id/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - google9abcd3b1ef946b3d.html

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
marked:
  prependRoot: true
  postAsset: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: officesupportjp

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: https://github.com/officesupportjp/blog.git
  branch: gh-pages # "gh-pages" is the  default for git type

github:
  url: https://github.com/officesupportjp/blog/
  posts_dir: articles

# hexo-generator-sitemap (https://github.com/hexojs/hexo-generator-sitemap)  
sitemap:  
  path: sitemap.xml


alias:
  (WebAPI)Microsoft Graph - OneDrive API (C Sharp) を使ったサンプル コード/index.html: cl0m8t2aa00013gvsa2mr8xj5/index.html
  (WebAPI)Microsoft Graph – Excel REST API (C Sharp) を使い Range を操作するサンプル コード/index.html: cl0m8t2a400003gvsgcr96w6h/index.html
  (WebAPI)Microsoft Graph を使用した開発に便利なツール群/index.html: cl0m8t2ae00033gvsbtlo3btc/index.html
  (WebAPI)OAuth Bearer Token (Access Token) の取得方法について/index.html: cl0m8t2ac00023gvs6bwo9tp2/index.html
  (WebAPI)OneNote API (C Sharp) を使いページ コンテンツを表示するサンプル コード/index.html: cl0m8t2ag00043gvs6dpf43ay/index.html
  (オートメーション - VSTO) .NET での Office ソリューション開発時の開発環境のバージョン選定 (最新版)/index.html: cl0mdnobv00055ovs67kp420v/index.html
  1 つの Web ページ上の Excel ファイルが 2 つ以上直接開けない件について/index.html: cl0m7gho00007k8vs5dodc5y4/index.html
  1. Office PIA 経由で Office 製品をオートメーションすることによる、Office オブジェクトモデルの操作/index.html: cl0mfb79f0006nwvs973z6w4v/index.html
  2016 年 7 月のセキュリティ更新プログラム MS16-088 適用後 Web 上の Excel に偽装したファイルが開けない/index.html: cl0m7gho60009k8vs2wd828cr/index.html
  2016 年 7 月セキュリティ更新プログラム MS16-088 の動作が変更されました/index.html: cl0m7ghnx0006k8vs0mra337a/index.html
  2017 年 7 月のセキュリティ更新適用後、VBA から一部のオブジェクトを作成できません/index.html: cl0mc9o0l000bb0vsf8n5en1k/index.html
  2020 年 4 月のセキュリティ更新による VBA からのネットワーク上の参照への影響/index.html: cl0m6umue000bi4vs38az4698/index.html
  2020 年 4 月の更新適用後、日本語を含む外部参照を行う VBA が読み込まれない問題/index.html: cl0m6umui000ci4vs1vcz49cz/index.html
  32bit の Word アプリケーションで、印刷した際に一部のオブジェクトが印刷されない現象について/index.html: cl0m7ghog000dk8vs2ovx9yyp/index.html
  Access 2013 以降の「クロス集計クエリ ウィザード」で列見出しとして最後のフィールドが利用できない/index.html: cl0m7ghof000ck8vscdxhanmb/index.html
  Access 2016 のリボンをカスタマイズする/index.html: cl0m7ghok000hk8vs3g1i3uwj/index.html
  Access でメモリ不足エラーが発生する現象の対処策について/index.html: cl0m7ghoi000fk8vs8yjpdr8b/index.html
  C2R 版の Office をインストールすると、特定のレジストリのアクセス権限テーブル参照時に警告が発生する/index.html: cl0m7ghoj000gk8vsf6s42i7t/index.html
  Excel - PowerPoint - Visio 2016 バージョン 1801 以降で WebBrowser コントロールがユーザーフォーム外に表示される/index.html: cl0mc9o0y000lb0vs0gt6dkmz/index.html
  Excel 2010 以降で条件付き書式を設定したブックへのコピー & ペーストに時間がかかる/index.html: cl0n10dcu000j90vsghpb14v9/index.html
  Excel 2013 からのウィンドウ管理方法変更について – シングル ドキュメント インターフェイス (SDI)/index.html: cl0n10dct000i90vs4c2a3pct/index.html
  Excel 2013 以降のバージョンでファイルを保護ビューで開くときにシート領域が描画されない/index.html: cl0n10dcv000k90vs6yxmbsb8/index.html
  Excel 2013 以降のバージョンで正しく横 (項目) 軸ラベルが更新されない/index.html: cl0n10dcz000n90vsaznd04om/index.html
  Excel 2016 for Mac での印刷時に先頭ページ番号の設定ができない – “First page number” is not effective when printing on Excel 2016 for Mac/index.html: cl0m7ghor000nk8vsf3ka62dj/index.html
  Excel 2016 ですぐに条件付き書式が反映されない/index.html: cl0n1lilx000nokvs9i0o288v/index.html
  Excel 2016 以降で結合セルの一部をコピーして貼り付けるとエラーが発生する/index.html: cl0m6umuw000pi4vsdxbv4vv5/index.html
  Excel for Microsoft 365 で上書きモードで DBCS を 1 文字を編集すると 2 文字分上書きされる/index.html: cl0m69xtr000o4cvs2pym5n2d/index.html
  Excel で ScrollArea プロパティを設定すると、キーボード操作でシートがスクロールしない/index.html: cl0m4xkiy000reovs1r3cadx0/index.html
  Excel でブックを開くプロセスを統合するメリット/index.html: cl0n10ddh000t90vsbpgv3r9l/index.html
  Excel に入力した記号のフォントが Cambria Math に変更される事象について/index.html: cl0m4xkiz000ueovs9w63bz08/index.html
  Excel の CodeName プロパティが取得できない動作/index.html: cl0mc9o14000tb0vs85lvc2xs/index.html
  Excel の SpecialCells メソッドで特定の状況において期待しない該当セルが取得される/index.html: cl0mc9o15000vb0vscpvphs5e/index.html
  Excel ユーザー定義関数に機能説明や独自ヘルプをリンクする方法/index.html: cl0mfb7ac000wnwvsen2873w5/index.html
  IRM 保護とパスワード保護を同時に付与したファイルを保存できない事象について/index.html: cl0m6umv2000xi4vsgyjudhkf/index.html
  IRM 暗号化ファイルを Office で利用する際に制限される機能について/index.html: cl0m7ghoz000yk8vsfakza883/index.html
  KB 3191877 の適用後に VBA のコンパイルエラーが発生する/index.html: cl0mc9o17000zb0vs3hta6j0c/index.html
  Large Address Aware に対応した Excel 2013 - Excel 2016/index.html: cl0m7opb80010dcvs1xqm1hbg/index.html
  Microsoft Forms でよく本サポートに寄せられるお問い合わせ/index.html: cl0m7opba0012dcvsezl78z14/index.html
  Microsoft Office 製品を Windows のプラットフォーム上で別アプリケーションから操作する場合のテクノロジについて/index.html: cl0mfb7ai0013nwvs9tsk91ry/index.html
  Microsoft ストア アプリ版 Office 2016 (Centennial) での開発 – その1 – (DLL の読み込み)/index.html: cl0mc9o1b0014b0vsbsrk3ew0/index.html
  MSI 版の Office 2016 で SPO、OneDrive、WebDavサーバーから Office ファイルが開かない、保存できない現象について/index.html: cl0m69xu000124cvsclmc5vis/index.html
  Office 2010 に Ogl.dll の更新プログラムが適用されない/index.html: cl0n1lim70016okvsef1sfvh1/index.html
  Office 2010 に Wwlibcxm.dll の更新プログラムが適用されない/index.html: cl0n1lim60015okvs47xm0v9h/index.html
  Office 2010-2013 (既定) と Office 365 ProPlus の共存環境で Office 365 ProPlus をバージョン 1710 に更新すると Excel の関連付けが Office 365 ProPlus に変更される事象について/index.html: cl0m7opbe0017dcvs06fk2wqc/index.html
  Office 2016 が行うインターネット接続について/index.html: cl0n10de0001a90vs28153y7h/index.html
  # 「　|  」が使用できないため削除　
  # Office 2016 アプリケーション起動時に「コンピューターに api-ms-win-crt-heap-|1-1-0.dll がないため、プログラムを開始できません。」等のメッセージが表示される現象について/index.html: cl0m7opbg0019dcvs7v7v1fkj/index.html
  Office 365 ProPlus で言語パックの追加に失敗する/index.html: cl0m75al0001amcvs0tsdeksn/index.html
  Office 365 ProPlus アプリケーションでバックステージビューのオンラインストレージを非表示にする方法について/index.html: cl0m7opbh001adcvs8wu5f0kk/index.html
  Office 365 Sway を PowerShell を使用して一括で有効化、無効化 (停止) する方法について/index.html: cl0n10de0001b90vsbowhgnig/index.html
  Office 365 Sway を PowerShell を使用して指定ユーザー単位で有効化、無効化 (停止) する方法について/index.html: cl0n10de1001d90vs6xzb5ynb/index.html
  Office 365 の Microsoft Forms を PowerShell を使用して一括で有効化、無効化 (停止) する方法について/index.html: cl0n10de1001e90vs1mrp11zq/index.html
  Office Online と Office デスクトップ アプリケーションの機能差異に関する情報/index.html: cl0m7opbk001fdcvs05wsecb0/index.html
  Office Viewer 製品の提供終了について/index.html: cl0m7opbl001gdcvs7kbb0ngv/index.html
  Office のサインインでネットワーク接続がない旨のメッセージが表示される事象について/index.html: cl0m75al4001gmcvse36w64dv/index.html
  Office のサインインのトラブルシュートについて/index.html: cl0m6umvg001gi4vsgppfcmk0/index.html
  Office のハイパーリンククリックで生じる問題への対処について (ForceShellExecute レジストリによる対処と影響)/index.html: cl0m7opbm001idcvs6pr2917a/index.html
  Office のパフォーマンス トラブルシュート (その 3：はじめに試す設定 - 描画編 -)/index.html: cl0m75al9001jmcvs2kbq9c9w/index.html
  Office のパフォーマンス トラブルシュート (その 4：はじめに試す設定 – 起動・オープン①、印刷編 -)/index.html: cl0m75alb001lmcvs4dxl1m81/index.html
  Office のパフォーマンス トラブルシュート (その 5：はじめに試す設定 – 起動・オープン② –)/index.html: cl0m6umvm001li4vsfcvbhwrc/index.html
  Office のパフォーマンス トラブルシュート (その 6：はじめに試す設定 - ファイル内容編 -)/index.html: cl0m6umvn001ni4vsevp6168h/index.html
  Office のパフォーマンス トラブルシュート記事 リンク集/index.html: cl0m75ald001omcvs2s1w06q8/index.html
  Office のプロセス インスタンス制御について/index.html: cl0n10de6001p90vsaa9n6gy8/index.html
  Office のライセンス再認証について/index.html: cl0m75alf001qmcvsf6zeacqg/index.html
  Office の既定のフォントを変更する方法/index.html: cl0m75alf001rmcvses4a67bp/index.html
  Office の自動更新が行われない事象について/index.html: cl0m75alh001tmcvsdyspb36m/index.html
  Office をマルチスレッドでオートメーションすることの危険性/index.html: cl0mfb7b4001tnwvs5vama7sz/index.html
  Office オートメーションで割り当てたオブジェクトを解放する - Part2/index.html: cl0mfb7b5001unwvs919y8d7e/index.html
  Office オートメーションで割り当てたオブジェクトを解放する – Part1/index.html: cl0mfb7b6001vnwvs3rv43evy/index.html
  Office サーバー サイド オートメーションの代替案について/index.html: cl0mfb7b8001xnwvs5pzxb66j/index.html
  Office サーバー サイド オートメーションの危険性について/index.html: cl0mfb7b7001wnwvshfp01l5u/index.html
  Office ファイルの SPO & OneDrive 移行におけるマクロ (VBA) 影響/index.html: cl0m4rqa2001y50vshhi75we2/index.html
  Office ファイルを開こうとすると、実際に開いているユーザーとは異なるユーザーが使用中と表示される/index.html: cl0m4xkju001zeovsftbsaen9/index.html
  Office プロセスを自プログラム専用にすることはできません/index.html: cl0mfb7bc0021nwvs6zie7xtv/index.html
  Office リボンをカスタマイズ - パート1 - (カスタマイズ手法と仕組み)/index.html: cl0mc9o210022b0vs0kgsgh76/index.html
  Office リボンをカスタマイズ – パート2 – (ファイルにカスタム XML を追加)/index.html: cl0mc9o200021b0vscp6jdedg/index.html
  Office リボンをカスタマイズ – パート3 – (VSTO ビジュアルなデザイナーでカスタマイズ)/index.html: cl0mc9o220024b0vs9oh30xtc/index.html
  Office リボンをカスタマイズ – パート4 – (VSTO XML でカスタマイズ)/index.html: cl0mdnodm00245ovs9qdfdvwi/index.html
  Office リボンをカスタマイズ – パート5 – (TIPS 1：既存メニューのカスタマイズ)/index.html: cl0mc9o210023b0vs43wag0a0/index.html
  Office リボンをカスタマイズ – パート6 – (TIPS 2：動的なカスタマイズ)/index.html: cl0mdnodn00255ovs9onm1o0p/index.html
  Office リボンをカスタマイズ – パート7 – (TIPS 3：特殊メニューのカスタマイズ)/index.html: cl0mdnodo00285ovs0fooh79h/index.html
  Office 利用時に storage.googleapis.com や cdn01.boxcdn.net への通信が発生する/index.html: cl4hy59k50027usvsc5k6cuto/index.html
  Office 展開ツール (16.0.12827.20268) で RemoveMSI 属性を使用すると 30041-1039-30050-1039 等のエラーメッセージが表示される/index.html: cl0m69xux00254cvs8a1nb7qn/index.html
  Office 展開ツール (16.0.13328.20356) で生じる事象について/index.html: cl0m69xv1002b4cvs76yt55d6/index.html
  Office 展開ツール ログによる Office 365 ProPlus のインストール確認について ( Logging 要素設定によるログの確認方法)/index.html: cl0m7opcg002adcvshfqe4ujr/index.html
  Office 製品の UserVoice のご案内/index.html: cl0m7opci002edcvsdxujfuvz/index.html
  Office 製品のサインインで先進認証が有効化、無効化されているかを確認する方法について/index.html: cl0m4xkk1002beovs87lwadzx/index.html
  Office 開発におけるパフォーマンス トラブルシュート (その 1：概要と対処方法)/index.html: cl0mdnodq002c5ovs8mkubxio/index.html
  Office 開発におけるパフォーマンス トラブルシュート (その 2：ボトルネックの特定)/index.html: cl0mdnodr002e5ovseybmbjk6/index.html
  Office 開発に関するサポート対象外の構成でのトラブルシュート (切り分けの進め方)/index.html: cl0mdnods002f5ovs3my7b12j/index.html
  Officeソリューション開発時の開発環境のバージョン選定について/index.html: cl0mfb7bn002inwvse5785nd7/index.html
  OneDrive などのクラウド上の日本語パスに格納されたファイルからのリンク貼り付けでエラーが発生する/index.html: cl0m6umw6002hi4vs2765aacl/index.html
  OneNote 2016 で全角入力から半角入力にすると「遊ゴシック」に切り替わる/index.html: cl0n1lin1002iokvs3pyk3svz/index.html
  OneNote 2016 で背景に設定した画像が印刷時にずれる/index.html: cl0m82yjg002hvovsbntp6llw/index.html
  OneNote の OCR 機能で読み取りにくい文字列がある/index.html: cl28oxvt6002ku8uj1ose6ej2/index.html
  PowerPoint Online で日本語フォントが変更される/index.html: cl0m69xv6002k4cvsan4d7rs0/index.html
  PowerShell の導入について/index.html: cl0m82yji002lvovs7o3d4qg9/index.html
  SCCM で Office365 ProPlus の更新プログラムが必要と判定されない/index.html: cl0m82yjj002nvovs5qg4he0l/index.html
  SharePoint Server など WebDAV が有効なサーバーから Office ファイルが開かない、保存できない現象について/index.html: cl0m82yjj002mvovs9cil5fgy/index.html
  Teams 上で Excel ファイルを開くと、フォント サイズのプルダウン メニューが正しく表示されない事象について/index.html: cl0m6umw9002mi4vse768hhor/index.html
  Teams、SPO、OneDrive、WebDavサーバーから Office ファイルが開かない、保存できない現象のトラブルシューティングについて/index.html: cl0m4xkk8002oeovs8ggucayv/index.html
  VDI 環境における Microsoft 365 Apps のライセンス認証について/index.html: cl0m69xv9002p4cvscqd9c9gu/index.html
  VSTO：.NET 3.5 で使用していた UserInclusionList クラスが .NET 4.0 以降は使用できない/index.html: cl0mdnodx002r5ovsfzvw5fh5/index.html
  Windows 10 Version 1607 上で Workbook.Close 実行後に Excel がエラーとなってしまうことがある問題について/index.html: cl0mdnody002s5ovs5vpp069a/index.html
  Windows 10 バージョン 2004 以降で VBA 関数 StrComp() で全角カナと半角カナが一致判定されない/index.html: cl0m69xvc002t4cvs5918c1f6/index.html
  Windows 10 バージョン 2004 以降で 半角カナのフォームを含んだ Access ファイルでエラーが発生する/index.html: cl0m69xvc002u4cvsgc7a3bfp/index.html
  Windows Firewall が無効化されていると Office の保護ビューが開けない/index.html: cl0m82yjo002vvovs6ze3b7ob/index.html
  Windows と Office のバージョンによる組み合わせについて/index.html: cl0m82yjn002uvovsc0a4anqo/index.html
  Word 2016 からメールを送信すると文字化けする/index.html: cl0mdnody002t5ovsb4fl3dku/index.html
  Word 2016 の 2018 年 3 月 セキュリティ更新プログラム KB4011730 を適用すると、ファイルを開くまたは保存時にクラッシュする/index.html: cl0m82yjp002xvovse8wf6e43/index.html
  WSFC 継続的可用性 (CA) が有効な共有フォルダーから Office ファイルが開けない/index.html: cl6q3dt1k0000ks3pemokg0de/index.html
  “Microsoft Barcode Control” について/index.html: cl0m82yjq002zvovsh02539lo/index.html
  「このコンピューターに組織内の別のアカウントが既にサインインしています」と表示される/index.html: cl0m4xkkf002zeovs7htveccc/index.html
  「プログラムにコマンドを送信しているときに、エラーが発生しました」のメッセージについて/index.html: cl0n1lin9002zokvsexey1pgh/index.html
  「最初に行う設定です」 ダイアログの制御/index.html: cl0m82yjv0031vovs37fefyqb/index.html
  【お知らせ】Office サポートチーム フォーラムについて/index.html: cl0n1linb0033okvs9wyq6kys/index.html
  お知らせ - Japan Office Client Support Blog について/index.html: cl0m4xkl00039eovs4fp4ffbt/index.html
  インターネットから Office ファイルを開く時にエラーとなる現象について/index.html: cl0m82yjx0035vovs9kilbsab/index.html
  インターネットから入手した Office ファイルのマクロがブロックされる既定の動作変更について (MC322553)/index.html: cl0m4f5o1003504vsa5tp25c2/index.html
  クイック実行形式 (C2R) と Windows インストーラー形式 (MSI) を見分ける方法/index.html: cl0m8t2dj00393gvs3r7oar2m/index.html
  クイック実行形式 Office 環境で、Office 以外のアプリケーションから Office の OLEDB-ODBC を利用できます/index.html: cl0m6umwp0037i4vsflq54qjb/index.html
  クイック実行形式の Office をインストールすると Office 以外のアプリケーションから ODBC - OLEDB が利用できない/index.html: cl0m8t2dl003b3gvs6w8z8co4/index.html
  クイック実行版の Office を展開している環境で Office のサインインに失敗する (ライセンス認証が失敗する)事象について/index.html: cl0m75amr003amcvsd7ms8h6l/index.html
  クリップボード アクセスの競合による Office でのコピー-貼り付け失敗/index.html: cl0m4xkl2003deovs5ntr794w/index.html
  ストア アドインを利用したファイルを一元展開で利用できるようになりました/index.html: cl6as2js40007m0u87h40erld/index.html
  ストア版 Office で既定のプリンターが反映されないことがある/index.html: cl0m75amu003dmcvs55iw1i57/index.html
  バージョン 2005 - 2006 で Office プロセスの終了が遅延する/index.html: cl0m69xw5003i4cvsdwhh72zc/index.html
  ボリュームライセンス版 Visio 2016 と Microsoft 365 Apps を共存インストールする方法について/index.html: cl0m8t2dr003j3gvsend6h2m8/index.html
  モバイル版の Office のトラブルシューティングについて/index.html: cl0m69xw5003g4cvs4ob5gcuy/index.html
  数式エディター 3.0 の機能削除について/index.html: cl0m8t2ds003k3gvsdsa5g21h/index.html
  日本語入力中に Office アプリケーションが異常終了する場合がある現象について/index.html: cl0m8t2dt003l3gvs4yrh2f4r/index.html
  暗号化された Office ファイルを保護ビューで開き、保護ビューが閉じた後、クライアントの %localappdata% フォルダ配下 Packages フォルダに oice_xx_xxxxxxxx_xxxxxxxx_xxxx フォルダが残存する/index.html: cl7pvphjn0000a46ygd3m4nro/index.html